#ifndef INCLUDE_DATAHUB_CLIENT_CONSTANT_H
#define INCLUDE_DATAHUB_CLIENT_CONSTANT_H

#include <stdint.h>

/* consumer */

#define LIST_SHARD_INTERVAL 1000l
#define MAX_JOIN_GROUP_TIMEOUT 5000l
#define MIN_CONSUMER_SESSION_TIMEOUT 60000l
#define MAX_CONSUMER_SESSION_TIMEOUT 180000l
#define MAX_COMMIT_OFFSET_RETRY_TIMES 5u
#define OFFSET_COMMIT_TIMEOUT 4000l
#define OFFSET_CHECK_TIMEOUT 1000l
#define FORCE_COMMIT_TIMEOUT_MS 5000l
#define MIN_TIMEOUT_FOR_START 5000l
#define CFG_READER_SELECT_EMPTY_SHARD_TIMEOUT_MS 10000l

#define DEFAULT_LIMIT_NUM 100
#define DEFAULT_RECORD_FETCH_QUEUE_LIMIT 10000
#define MIN_TIMEOUT_WAIT_FOR_GROUP_READ 5000l
#define MAX_TIMEOUT_WAIT_FOR_GROUP_READ 60000l
#define CFG_DELAY_TIMEOUT_FOR_NOT_READY 2000l

#define RECORD_CACHE_MIN_NUM 1000u
#define MIN_TIMEOUT_WAIT_FETCH 5000l
#define FORCE_RECORD_LIMIT 10000l
#define DELAY_TIMEOUT_FOR_READ_END 2000l

#define DEFAULT_RETRY_TIMES 3
#define DEFAULT_FETCH_THREAD_NUMBER 16
#define DEFAULT_QUEUE_LIMIT_NUMBER 1024
#define MIN_FETCH_THREAD_NUMBER 2
#define MAX_FETCH_THREAD_NUMBER 500

#define UPDATE_TOPIC_META_INTERVAL 1000l
#define UPDATE_SHRAD_META_INTERVAL 1000l
#define SYNC_GROUP_MIN_INTERVAL 10000l

/* producer */
#define DEFAULT_MAX_ASYNC_BUFFER_TIME_MS 100l
#define DEFAULT_MAX_ASYNC_BUFFER_SIZE 4000000l
#define DEFAULT_MAX_ASYNC_BUFFER_RECOED_COUNT 10000l
#define DEFAULT_MAX_RECORD_PACK_QUEUE_LIMIT 1024

#endif // INCLUDE_DATAHUB_CLIENT_CONSTANT_H
